title: Pixel Ratios
description: Aspect ratio calculators for various formats
url: http://localhost:4000
# https://pixelratios.com
baseurl: ""

# Build settings
source: src
destination: web
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/

# Include files
include:
  - pages

