title: Pixel Ratios
description: Aspect ratio calculators for various formats
url: "https://codesigns-company.github.io/aspect-ratio-calculator"
baseurl: ""

# Build settings
source: src
destination: web
markdown: kramdown
highlighter: rouge
theme: minima
keep_files: [assets]

# Plugins
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/

# Include files
include:
  - pages

